### ISSUE TITLE
fig1 code

### ISSUE THREAD

**Issue by endaoguansanlu** [shiwt03/MUSTER#1]
Thank you so much for your outstanding work! I am very interested in your visualization work in Figure 1, could you please share the code? Looking forward to your reply!

**Comment by CA-TT-AC** [comment]
I am glad for your insterest in our work! It is a demo code of visualization, and you can use hook or just save the feature map in a file to use the visulization function.
```
import cv2
from PIL import Image
import matplotlib.pyplot as plt
def visulize_attention_ratio(img_path, attention_mask, save_path, ratio=0.5, cmap="jet"):
    """
    img_path: path of original image
    attention_mask: 2-dimension numpy array
    ratio:  enlarge or reduce ratio of the scale of the picture (optional)
    cmap:   the style of attention map (optional)
    save_path: path of the purpose image
    """
    print("load image from: ", img_path)
    # load the image
    img = Image.open(img_path, mode='r')
    img = img.resize((618, 512))
    img_h, img_w = img.size[0], img.size[1]
    plt.subplots(nrows=1, ncols=1, figsize=(0.02 * img_h, 0.02 * img_w))
    # scale the image
    img_h, img_w = int(img.size[0] * ratio), int(img.size[1] * ratio)
    img = img.resize((img_h, img_w))
    plt.imshow(img, alpha=1)
    plt.axis('off')
    # normalize the attention mask
    mask = attention_mask
    mask = cv2.resize(mask, (img_h, img_w))
    normed_mask = mask / mask.max()
    normed_mask = (normed_mask * 255).astype('uint8')
    plt.imshow(normed_mask, alpha=0.5, interpolation='nearest', cmap=cmap)
    f = plt.gcf()
    f.savefig(save_path)
```

**Comment by endaoguansanlu** [comment]
Thank you very much!^_^

**Comment by endaoguansanlu** [comment]
Hello, I don't know how to use hooks or store feature maps in mmsegmentation. Could you please give me a demonstration? For example, if I visualize the attention map of a certain layer of UperFormer, what should I do? Looking forward to your reply! Thanks!

**Comment by CA-TT-AC** [comment]
Actually, I use an off-line method to visualize feature maps. For example, if u need to visualize feature maps from different heads you can save information in such way:
```
# where i means the index of stage
for j in range(self.num_heads[i]):
    save_data = torch.sum(save_data, dim=2)
    save_data = save_data.squeeze(dim=0)
    save_data = save_data.view(hw_shape[0], hw_shape[1])
    save_data = np.array(save_data.cpu())
    # where self._count means the index of picture
    path = r'attention_map/result/result' + str(self._count) + '_' + str(j) + '.txt'
    np.savetxt(path, save_data)
```
And after u have saved what u want, u can open the txt file in such way:
```
attention_mask = np.loadtxt(path)
visulize_attention_ratio(img_path, attention_mask)
```
I hope this helps~

**Comment by endaoguansanlu** [comment]
Thank you so much for your quick reply! Sorry, I still have one last question. Does the "save_data" in the demo you give refer to the feature map of each head? If so are you saving them during inference? Looking forward to your reply! thank you very much!

**Comment by CA-TT-AC** [comment]
Absolutely right.

**Comment by endaoguansanlu** [comment]
I got it! Thank you for your patient reply!
